# Generated by Django 4.2.17 on 2025-01-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('help_type', models.CharField(choices=[('financial', 'Financial Assistance'), ('medical', 'Medical Care'), ('housing', 'Housing Support'), ('daily', 'Daily Care Support'), ('emotional', 'Emotional Support'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('immediate', 'Immediate (Within 24 hours)'), ('urgent', 'Urgent (Within a week)'), ('normal', 'Normal (Within a month)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
